// web-fullstack/web/src/components/Admonition/Admonition.tsx
/* SPDX-License-Identifier: AGPL-3.0-only
 *
 * This file is part of HarTex.
 *
 * HarTex
 * Copyright (c) 2021-2022 HarTex Project Developers
 *
 * HarTex is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * HarTex is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with HarTex. If not, see <https://www.gnu.org/licenses/>.
 */

import type { IAdmonitionProps } from "@components/Admonition";
import { ComponentType, ReactNode } from "react";

type AdmonitionTypeConfig = {
  iconComponent: ComponentType,
  title: ReactNode,
}

const WarningAdmonitionIcon = () => {
  return (
    <svg className="inline-block h-[1.6em] w-[1.6em]" viewBox="0 0 16 16">
      <path
        fillRule="evenodd"
        d="M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"
      />
    </svg>
  )
}

const configs: Record<IAdmonitionProps['type'], AdmonitionTypeConfig> = {
  warning: {
    iconComponent: WarningAdmonitionIcon,
    title: "warning"
  }
}

function extractAdmonitionConfig(admonitionType: string): AdmonitionTypeConfig {
  const config = (configs as {[key: string]: AdmonitionTypeConfig})[admonitionType];

  return config ? config : configs.warning;
}

const Admonition = (props: IAdmonitionProps) => {
  const admonitionConfig = extractAdmonitionConfig(props.type)
  const title = props.title ?? admonitionConfig.title
  const icon = props.icon ?? <admonitionConfig.iconComponent />

  return (
    <div className="mb-4">
      <div className="uppercase mb-[0.3em]">
        <span className="inline-block align-middle mr-[0.4em]">{icon}</span>
        {title}
      </div>
      <div>
        {props.children}
      </div>
    </div>
  )
}

export default Admonition

// web-frontend/components/Admonition.vue
<!--
  - SPDX-License-Identifier: AGPL-3.0-only
  -
  - This file is part of HarTex.
  -
  - HarTex
  - Copyright (c) 2021-2024 HarTex Project Developers
  -
  - HarTex is free software; you can redistribute it and/or modify
  - it under the terms of the GNU Affero General Public License as published by
  - the Free Software Foundation; either version 3 of the License, or
  - (at your option) any later version.
  -
  - HarTex is distributed in the hope that it will be useful,
  - but WITHOUT ANY WARRANTY; without even the implied warranty of
  - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  - GNU Affero General Public License for more details.
  -
  - You should have received a copy of the GNU Affero General Public License along
  - with HarTex. If not, see <https://www.gnu.org/licenses/>.
  -->

<template>
  <div :class="[type]">
    <div class="heading">
      <svg class="icon" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z"/></svg>
      {{title}}
    </div>
    <ContentSlot :use="$slots.default" unwrap="p" />
  </div>
</template>

<script setup lang="ts">
defineProps<{
  title: string,
  type: string
}>()
</script>

<style>
.icon {
  display: inline-block;
  margin-right: .3rem;
  vertical-align: middle;
}

.warning .heading .icon {
  fill: #FFF7E6;
}

.warning {
  background-color: #FFCC6655;
  border: 0;
  border-left: 5px solid #FFCC66;
  border-radius: 7px;

  @apply p-5 my-4;
}

.warning .heading {
  box-sizing: border-box;
  margin-bottom: .3rem;

  color: #FFF7E6;

  @apply font-bold;
}

</style>
