// web-fullstack/web/src/components/Navbar/Navbar.tsx
/* SPDX-License-Identifier: AGPL-3.0-only
 *
 * This file is part of HarTex.
 *
 * HarTex
 * Copyright (c) 2021-2022 HarTex Project Developers
 *
 * HarTex is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * HarTex is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with HarTex. If not, see <https://www.gnu.org/licenses/>.
 */

const Navbar = () => {
  return (
    <header className="fixed w-screen">
      <i className="fa-solid fa-bars block xl:hidden text-right"></i>
      <nav className="hidden xl:block">
        <ul className="text-right">
          <li>
            <i className="fa-brands fa-github"></i>
          </li>
          <li>
            <i className="fa-brands fa-discord"></i>
          </li>
          <li>
            <i className="fa-solid fa-book"></i>
          </li>
          <li>
            <i className="fa-solid fa-circle-user"></i>
          </li>
        </ul>
      </nav>
    </header>
  )
}

export default Navbar

// web-frontend/components/Navbar.vue
<!--
  - SPDX-License-Identifier: AGPL-3.0-only
  -
  - This file is part of HarTex.
  -
  - HarTex
  - Copyright (c) 2021-2022 HarTex Project Developers
  -
  - HarTex is free software; you can redistribute it and/or modify
  - it under the terms of the GNU Affero General Public License as published by
  - the Free Software Foundation; either version 3 of the License, or
  - (at your option) any later version.
  -
  - HarTex is distributed in the hope that it will be useful,
  - but WITHOUT ANY WARRANTY; without even the implied warranty of
  - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  - GNU Affero General Public License for more details.
  -
  - You should have received a copy of the GNU Affero General Public License along
  - with HarTex. If not, see <https://www.gnu.org/licenses/>.
  -->

<template>
  <header class="navbar">
    <NuxtLink class="brand" to="/">HarTex</NuxtLink>
    <Icon name="carbon:menu" />
    <nav>
      <ul>
        <li><NuxtLink to="/">Documentation</NuxtLink></li>
      </ul>
      <ul>
        <li>
          <NuxtLink to="https://github.com/TeamHarTex/HarTex">Github</NuxtLink>
        </li>
      </ul>
      <ul>
        <li>
          <a v-on:click="">Login/Register</a>
        </li>
      </ul>
    </nav>
  </header>
</template>

<style lang="postcss" scoped>
.navbar {
  @apply flex flex-row pt-16;
  @apply items-center justify-between;
}

.brand {
  @apply text-2xl sm:text-4xl text-secondary;
}

nav {
  @apply hidden sm:block;
}

nav ul {
  @apply inline-block mx-6 first:ml-0 last:mr-0;
}

svg {
  @apply visible sm:invisible text-2xl;
}
</style>
